// This is a stub file for build purposes
// The real file will be generated by Convex when running `npx convex dev`

export type Id<Table extends string = string> = string & { __brand: "Id" };

export interface DataModel {
  players: {
    _id: Id<"players">;
    username: string;
    deviceId: string;
    statsId: Id<"stats">;
    createdAt: number;
    lastSeen: number;
  };
  rooms: {
    _id: Id<"rooms">;
    code: string;
    hostId: Id<"players">;
    status: "waiting" | "playing" | "finished";
    difficulty: string;
    createdAt: number;
  };
  participants: {
    _id: Id<"participants">;
    roomId: Id<"rooms">;
    playerId: Id<"players">;
    isHost: boolean;
    isReady: boolean;
    bullets: number;
    roundsWon: number;
  };
  moves: {
    _id: Id<"moves">;
    roomId: Id<"rooms">;
    roundNumber: number;
    playerId: Id<"players">;
    action: string;
    timestamp: number;
  };
  stats: {
    _id: Id<"stats">;
    playerId: Id<"players">;
    multiplayerWins: number;
    multiplayerLosses: number;
    bestStreak: number;
    totalRounds: number;
  };
}

// Stub function types - these will be replaced by Convex-generated types
export const api = {
  players: {
    createAnonymousPlayer: null as any,
    updateLastSeen: null as any,
    getPlayer: null as any,
    getPlayerStats: null as any
  },
  rooms: {
    createRoom: null as any,
    joinRoom: null as any,
    toggleReady: null as any,
    leaveRoom: null as any,
    getRoomByCode: null as any,
    getParticipants: null as any,
    getRoomWithParticipants: null as any
  },
  games: {
    makeMove: null as any,
    resolveRound: null as any,
    recordGameResult: null as any,
    getMoves: null as any,
    getCurrentRound: null as any,
    getLeaderboard: null as any
  }
};
